### ISSUE TITLE
[feature request] dashboard筛选出来的counter 直接保存为screen

### ISSUE THREAD

**Issue by laiwei** [XiaoMi/open-falcon#12]

**Comment by laiwei** [comment]
https://github.com/open-falcon/dashboard/issues/6

**Comment by modeyang** [comment]
和@聂安 讨论过， 多个关键字搜索时，看代码是用and操作，可能我想用or操作，同时想查看多个counter的图。 
可以增加个选择项选定用哪种搜索连接关系就好了。

**Comment by laiwei** [comment]
嗯，这个and的动作，参考的是google的搜索框，多个关键字同时检索。

**Comment by yubo** [comment]
快照功能下个版本会支持
