### ISSUE TITLE
[feature request] 接驳服务树（CMDB）

### ISSUE THREAD

**Issue by laiwei** [XiaoMi/open-falcon#14]
open-falcon现在采用扁平的、一维的hostgroup来管理机器，在机器规模较大的时候，管理成本较高

与CMDB接驳，是一个好的方案。

**Comment by lyonliquid** [comment]
在没有接驳cmdb的情况下，监控portal和dashboard里面都需要维护机器列表，这个在多分组的情况下很不好管理

**Comment by forevergao** [comment]
什么时候会有接驳CMDB的版本出来？

**Comment by 397849270** [comment]
same problem! @forevergao

**Comment by yubo** [comment]
小米内部的新版falcon，以及实现了独立的服务树以及权限，角色管理，稍后放出

**Comment by modeyang** [comment]
@yubo  服务树大概什么时候能开源？

**Comment by fremindmm** [comment]
> 小米内部的新版falcon，以及实现了独立的服务树以及权限，角色管理（与公司内部的服务树解耦合了），稍后放出

有服务树的版本 什么时候放出来？

**Comment by UlricQin** [comment]
试试夜莺吧，带有完备的服务树：https://github.com/didi/nightingale
