### ISSUE TITLE
关于告警judge模块的一些分析和建议

### ISSUE THREAD

**Issue by harryshayne** [XiaoMi/open-falcon#15]
关于告警judge模块的一些分析和建议：
1、expression是单独与某个endpoint关联，使用tag来匹配。
优点：可以灵活根据tag对metric进行匹配，
缺点：用户必须把expression书写正确
2、strategy是专门和template绑定的，template中还会指定action，因此template所有策略的触发只能对应一个action，而不能对不同的策略进行不同的action，这显然不够灵活；另外action是不能复用的， 每一个action都只能跟随某个template或者expression，删除了template也会删除对应的action，但是删除了 expression不会删除对应的action，这点估计是个bug；值得一提的是，某个strategy也是只能关联一个template，并且会随 着template删除而删除。
优点：可以直接在模板界面对其进行修改，strategy和template在逻辑上是一种从属的关系，所以对strategy的改动不会影响其他template，用户使用也较为方便，自上而下进行操作，
缺点：无法复用。
3、template的设计是每个template都拥有自己的strategy和action， 最好就是可以都设计到一张表中，但是由于要拥有多个strategy，所以只能是另外开张表来保存strategy，所以strategy是不能复用的。 对于用户的使用而言，endpoint为host时必须通过hostgroup来间接关联template。另外，template通过关联user决定发给那个用户
优点：与2类似，一个template决定了所有的逻辑，并且这些逻辑与其他template是独立的，所以方便编辑修改template，而不会影响其他template
缺点：无法复用
4、hostgroup的设计是所有host都可以属于多个hostgroup，hostgroup再bind多个template，顺藤摸瓜就找到strategy。hostgroup其实就是一种分类，一种扁平化的结构，和我们meleors的分组有点不同。
优点：host可以灵活分到多个组
缺点：新增一个机器，可能需要让它同时属于多个组，配置稍微麻烦（改进的方法就是采用树形结构咯）,另外一个就是策略冲突比较难以发觉
5、一个数据是既可以和expression也可以和strategy关联的。对于endpoint非host的可以直接和 expression关联，不过这种关联只是通过expression中的一个表达式tag来表示的，并没有一个关联表

**Comment by harryshayne** [comment]
@UlricQin 关于第三点和第四点可能改进吗？

**Comment by laiwei** [comment]
关于4，参考 https://github.com/XiaoMi/open-falcon/issues/14

关于3，目前尚无计划
