### ISSUE TITLE
[feature request] 曲线图支持自动定时刷新

### ISSUE THREAD

**Issue by huangzhizhong** [XiaoMi/open-falcon#16]
1. ajax局部刷新
2. 可按单张曲线图定义
3. 刷新间隔时间可定义
4. 默认关闭

**Comment by laiwei** [comment]
谢谢建议

我们规划在下一个milestone来支持，或者你也可以直接提交pull-request来解决：）

**Comment by sfsw** [comment]
这个可以有，报表图无法实时显示确实很不方便，现在我都只能用浏览器定时刷新，希望这个功能尽快上

**Comment by yubo** [comment]
已修复 https://github.com/open-falcon/falcon-plus/commit/272db4f72088c3631d2f6184eca4f7e872ac5535
管道阻塞问题
