### ISSUE TITLE
自定义指标在图表页线是断的.

### ISSUE THREAD

**Issue by bshy522** [XiaoMi/open-falcon#18]
主要这个自定义的指标不是连续的值. 在没有时, 就没上报. 请问是否可以增加设置, 如果当某个时间段的指标值没有的话  默认给个0  让线能够连续起来.

谢谢

**Comment by bshy522** [comment]
![image](https://cloud.githubusercontent.com/assets/1124573/10507434/f41e8f24-7352-11e5-8045-23761bfda2f5.png)

**Comment by laiwei** [comment]
用0连起来，不适合大多数场景

**Comment by bshy522** [comment]
可以配置吗?

**Comment by laiwei** [comment]
不能配置呢
因为原本就是这么设计的

**Comment by bshy522** [comment]
哦哦, 好的 谢谢回答.
