### ISSUE TITLE
在Windows上部署的问题？

### ISSUE THREAD

**Issue by tensafe** [XiaoMi/open-falcon#19]
* 首先很感谢小米同仁开源的精神
* 下载代码后，尝试在Windows平台上编译使用，初步测试除Agent,Graph两个组件之外，其它组件没有问题
* Agent移植的问题不大
* Graph移植时，需要解决rrdtool编译问题
* 正常编译后，还需要解决在Windows平台创建rrd文件只读，导致数据无法保存的问题
* 不知道小米同仁是否也有此类需求？（目测所有的系统均部署在Linux?）

**Comment by laiwei** [comment]
目前推荐方案是:
- open-falcon的服务端，整体部署在Linux平台上。
- 运行一组windows平台的脚本，来采集windows机器的各项指标，通过API推送给open-falcon

该组脚本，可以参考 http://book.open-falcon.com/zh/index.html

**Comment by tensafe** [comment]
* 我有一个修改后能正常编译的rrdlite，这样的话，就可以整体部署在Windows。可否看一下吗？
* 另外问个问题： transfer这个版本没有将原始数据打入opentsdb或其它地方吧？貌似没有找到任何的代码呢？这种情况是让transfer打入原始数据还是另外开一个新的模块来做这个事儿呢？

**Comment by laiwei** [comment]
@tensafe 

1. 估计要趟一些坑，不过原则上感觉可以
2. 现在数据只发送给graph存储起来的。具体代码可以参考transfer发送数据部分。如果要发送一份到opentsdb，那么需要增加transfer的代码

**Comment by tensafe** [comment]
* 谢谢
