### ISSUE TITLE
[feature request] 历史数据支持存取opentsdb

### ISSUE THREAD

**Issue by laiwei** [XiaoMi/open-falcon#21]
opentsdb作为一款很流行的、基于hbase的 时间序列的数据存储引擎，有很多成熟的数据展示组件适配了opentsdb，因此openfalcon适配tsdb的话，能让用户多一种数据可视化的选择方案。

**Comment by qiaohaijun** [comment]
opentsdb的读取性能如何？

**Comment by laiwei** [comment]
@qiaohaijun 读取性能较低。

**Comment by 15089651115** [comment]
那么其他方面怎样

**Comment by yubo** [comment]
开源版本已经支持tsdb 后端存储
