### ISSUE TITLE
插件运行方式不以文件前缀名字方式执行，而在portal中配置

### ISSUE THREAD

**Issue by modeyang** [XiaoMi/open-falcon#22]
如题，这种运行逻辑对于插件的运行管理会更加的灵活。谢谢

**Comment by laiwei** [comment]
脚本的输出，是符合falcon的格式的，即输出的内容中是要有step字段的。

所以就算把脚本的前缀的step放在数据库中配置，也避免不了要修改脚本里面代码

所以这个方案会更复杂。。。
