### ISSUE TITLE
URL监控

### ISSUE THREAD

**Issue by modeyang** [XiaoMi/open-falcon#23]
open-falcon能否支持url监控，可以在portal上面做配置，指定hostgrp去做url探测。
不知道是否有计划？

**Comment by laiwei** [comment]
这个没有在规划里面。

open-falcon更多的是提供一个框架，url探测建议用户自己做探测，把结果push到open-falcon即可。

**Comment by onlymellb** [comment]
我们在open-falcon基础上实现了在portal 配置url探测下发功能，修改下hbs的代码和agent的代码即可支持

**Comment by laiwei** [comment]
@onlymellb 
是否可以发个PR看看？

**Comment by onlymellb** [comment]
已经提了，hbs一个，agent一个 @laiwei

**Comment by laiwei** [comment]
:+1: 非常赞 我来看看，谢谢

https://github.com/open-falcon/agent/pull/27

https://github.com/open-falcon/hbs/pull/4

**Comment by onlymellb** [comment]
顺便在提一个问题，open-falcon的前端登陆权限那块做的有点问题。。。具体就是只要在fe模块登陆后，然后点开portal进去，这时你在fe首页点击退出账号后，会发现点进去portal仍然是之前登陆过后的账号，也就是说，在fe模块点击退出这个动作，只是将fe这边cookie中的sig字段清空，然而并没有影响到portal那边的cookie

**Comment by modeyang** [comment]
@onlymellb  portal中应该还有一个pr吧， URL在portal中配置。

**Comment by modeyang** [comment]
大赞 @onlymellb

**Comment by modeyang** [comment]
我觉得在curl 前面加个time 去获取ping每个url的所需时间，加个req_time这样的tag会不会也可以？

**Comment by onlymellb** [comment]
@modeyang  portal并没有pr,增加这个功能不需要修改portal,只需配置报警的时候写url.check.health,然后tag一栏里面写url="http://www.xxx.xxx/xxx,timeout=3",tag里面指定需要探测的url以及超时时间，时间单位为秒，就是探测的时候超过timeout没响应则探测失败

**Comment by laiwei** [comment]
嗯，我会尽快review的：）

**Comment by modeyang** [comment]
@onlymellb  看了代码  知道这个规则了  我说的第二个问题  加个请求时间的tag 可否实现？

**Comment by UlricQin** [comment]
agent做url探测？agent有很多的，同一个url岂不是会探测多次？这个功能最好不要放在agent里。url探测就像ping监控，可以单独搞一个组件

**Comment by laiwei** [comment]
@onlymellb  @UlricQin 

我前几天在考虑，url探测，放在agent中是否合理。

url探测，作为一个非常常见的需求，open-falcon能够内置支持是非常好的。
从用户使用的角度来讲，我作为用户，有一组服务器，安装了agent，专门用来做URL探测用，这时候，在portal中绑定url_check_health的metric，也是非常方便的。

@onlymellb
这个PR，有下面几个地方希望能改改:
- 把url.check.health定义成一个常量吧。
- 调用curl命令的时候，加一个防御性的参数--max-filesize=102400。另外在文档中，明确告诉用户 URL.check.health 只支持HTTP(S) FTP(S)，且大小不超过10M，并以判断http_code是否为200作为成功与否的判定标准。
- 上报的结果里面，加一个额外的tag，src_ip=xxx，xxx表示agent的ip，一方面排查方便，另一方面多个agent执行同一个URL检测 可以区分开。


谢谢:)

**Comment by onlymellb** [comment]
@laiwei  其余三个builtin的内置监控项也没有定义成常量啊，因此这个url.check.health也没必要定义成常量吧？(我尽量和之前的代码风格保持一致)  防御性参数和src_ip的tag已添加，本地测试没问题.

**Comment by laiwei** [comment]
@onlymellb  顺便把另外几个builtin的监控项，也定义为常量吧：）辛苦啦

**Comment by onlymellb** [comment]
@laiwei  改完🐦

**Comment by laiwei** [comment]
@onlymellb 已合并，另外我做了一点点改动，你可以查看下。谢谢

**Comment by kame000** [comment]
@laiwei   有时间是否可以写个简单的文档，对于go的小白，很难理解。
这个需求确实也是大多数人想要有的一个需求。
谢谢！

**Comment by xiaoyaolaotou** [comment]
现在0.2的版本是否支持URL探测？是否有文档？
