### ISSUE TITLE
portal 中expression支持合并报警

### ISSUE THREAD

**Issue by modeyang** [XiaoMi/open-falcon#24]
比如交换机流量报警，each(metric=switch.if.Out ifName=Eth-Trunk1)写了这样的expression表达式，
采用了pdiff（#3）> 50 的触发报警，但是这种触发条件对于小流量但是波动频繁的情况报警太多，因为总流量太小（比如从20M上升到40M）根本就构不成报警，如果此时添加个max（#3）> 1G这样的合并触发条件，就可以屏蔽掉很多告警。
不知道有没有什么好的方式解决这种问题呢？

**Comment by laiwei** [comment]
这个目前在open-falcon的设计机制下，很难实现。

我们后续想想怎么来折中解决
