### ISSUE TITLE
建议和反馈

### ISSUE THREAD

**Issue by laiwei** [XiaoMi/open-falcon#27]
更多信息  http://book.open-falcon.com/zh/index.html

**Comment by frostynova** [comment]
我来提两个：

* 报警策略目前没有 api 接口，无法做到自动化添加报警策略
* 绘图也没有接口，如果能像 graphite 那样传递一个正则给绘图接口，然后输出图片就能很方便的进行 dashboard 定制和监控嵌入了

**Comment by Luoyoung** [comment]
外观：网页语言统一，要么全中文，要么全英文，最好中英文可以互相切换。几个组件网页风格统一（包括图标）

**Comment by Luoyoung** [comment]
功能：
1.	实现用户组权限分配、管控，哪些人只能查看，哪些人只能查看哪些Endpoint或者Counter，Dashboard只能呈现User有权查看的。哪些人可以管理报警策略，哪些人可以管理哪些报警策略；
2.	统一入口，未登陆用户查看任何网页直接跳转用户登录网页，只能登录后才能查看管理Open-Falcon。目前OpsPlatform的平台登录/退出不直观，用户需要点击它才知道有没有登录，应该是先登录再进OpsPlatform。目前Dashboard和未恢复的报警不登录也可以查看，不科学；
3.	Dashboard应该直接自动分页列出所有Endpoint，留一个搜索框快速搜索，这样比较直观；
4.	Dashboard可以设置自动刷新开关，方便展示；
5.	实现资产统计功能，自动发现设备配置，生成清单网页，支持导出；
6.	实现监控报表统计功能，统计每周或每月整个系统运行情况，报警总数统计，报警事件概括。每月自动生成监控报表并自动通过邮件发送给相关负责人，让负责人知道自己管理系统或机器的健康情况；
7.	增加Windows Agent，毕竟有很多公司服务器多数还是Windows server。注册为Windows服务，方便快捷。现在的定时运行python脚本虽然能实现初步功能，但是部署麻烦，每台还要装python环境；
8.	增加统一的http邮件接口服务，每个公司邮件无非也就是SMTP或者Exchange，有的开了SSL，有的又没开。

**Comment by freedomkk-qfeng** [comment]
现在dashboard的数据显示单位都是按1000计算的。即1000=1K，100000=1M，....
但是对于磁盘容量，网络数据等，似乎按1024计算更为合适。
建议可以在dashboard的图边上增加个选项，选择计算方式为1000还是1024~~

**Comment by yinchuan** [comment]
metric 不能用中文名字。
我用下面的命令测试：
```
curl -X POST -d '[{"metric":"中文", "endpoint": "open-falcon-graph01.bj", "timestamp": 1431347802, "step": 60,"value": 9,"counterType": "GAUGE","tags": "project=falcon,module=graph"}]' http://127.0.0.1:1988/v1/push
```
返回的是`success`，但 Dashboard 中看不到这个 metric，其他用英文名字的就能正常看到。

**Comment by yinchuan** [comment]
> 报警策略目前没有 api 接口，无法做到自动化添加报警策略
这个也是很需要的。

另外，一般来说每个反馈都开一个 issue，然后打上对应的 tag 会比较简单吧，这样每个反馈还可以单独讨论，不会串在一起；fix 之后也只可以直接用 close #xxx 什么的来直接 close。

**Comment by laiwei** [comment]
@yinchuan 这个issue是用来给大家做反馈和建议的初步收集。

具体可以操作的，很明确的，纳入规划中的，都是会更新到issue列表和相应的milestone

**Comment by yinchuan** [comment]
@laiwei 我理解这个 issue 的作用，只是觉得这样不够方便。
1. 不能针对某个 comment 做讨论和交流，同样没办法针对某个 feature request 或 bug 投票。同样，反馈者会收到很多并也许不关心的邮件 notification，也是一种干扰。
2. 如果某个 comment 中的建议可以执行了，谁建 issue，原来的 comment 不能方便地通过 PR close。而且新建 issue 会丢失讨论过程。
3. 另外，开 issue 的数量可以作为一个项目是否活跃、用户是否多、用户活跃度的指标，这对于新用户是否使用这个项目影响蛮大的；对维护者来说，活跃的用户社区也是一种激励。

所以，我的建议是每个反馈都开新 issue，维护者给 issue 打上 feature request, bug, need more info 等标签，在排开发计划的时候再打上 milestone。这样的好处是作为反馈者的体验很完整，能够知道项目维护者是否得到了准确的反馈，其他人是否有相同建议或问题或补充，如果有 milestone，还能预期什么时间能解决，最后也能知道是哪个 PR close 的这个 issue。当新用户通过搜索找到这个 issue 的时候，能够回顾全部的历史。

**Comment by itxx00** [comment]
@yinchuan  你们也在用吗？

**Comment by yinchuan** [comment]
我也在评估，准备试试。

On Wed, Jan 6, 2016 at 9:22 PM, Well <notifications@github.com> wrote:

> @yinchuan <https://github.com/yinchuan> 你们也在用吗？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/XiaoMi/open-falcon/issues/27#issuecomment-169321719>.
>



-- 
尹川 架构组SA
QQ: 254113859
微信: $QQ
Google Plus: yinchuan.blue@gmail.com

**Comment by thuhak** [comment]
功能：
       能否增加一个标准的轮询框架。很多时候部署客户端还是比较麻烦的，用通用管理协议进行轮询方便一些。就比如说把snmp，wmi，jmx，telnet,ssh各种采集协议的轮询部分摘出来，单独做个标准框架。

**Comment by thuhak** [comment]
功能：
     针对vmware vsphere可以考虑把agent做在vmware tools里。在vc上只需要部署一台appliance server 就ok了，部署起来非常方便

**Comment by qingchn** [comment]
不好意思冒昧了，我提一点。
能不能报表功能，展示每周，每月，每年（可以定义时间）时间周期内服务器相关负载，应用相关QPS等。

**Comment by itxx00** [comment]
@qingchn  你要的功能现在的dashboard应该就能满足吧

**Comment by lyonliquid** [comment]
@laiwei 在未恢复的报警那里，是否可以提供一个可以批注的地方，对于长期无法恢复的报警，可以做一个文字注解

**Comment by stoneluo** [comment]
如果想在监控邮件，添加一些业务数据的内容，应该如何实现？
想用falcon callback接口，但是不知道接口api，或者其他思路？

**Comment by 397849270** [comment]
@laiwei ，你好，我们再实际配置告警时，发现portal中的hostgrp组后面有hosts,templates,plugins,aggregator,在实际告警接收组中能不能也支持按照hostgrp进行配置，而不是配置在templates里面，这样就可以解决策略继承时，告警组不同步继承的问题。

**Comment by yubo** [comment]
有问题单独再开，这个关闭了。
今年夏季会推出v0.2（falcon-plus）
