### ISSUE TITLE
agent  占用比较多的内存

### ISSUE THREAD

**Issue by yi719** [XiaoMi/open-falcon#29]
agent  启动以后就会占用300多M的内存 ，  跑 一段时间 以后更  占内存了
781.64 Mb ./falcon-agent -c cfg.json

这个是我配置的问题么

**Comment by laiwei** [comment]
700M 也不错多吧。。。

**Comment by yi719** [comment]
好吧， 因为不太清楚 Agent  的设计 ， 所以700M是属于正常情况 ？

**Comment by yubo** [comment]
已修复， https://github.com/open-falcon/falcon-plus/commit/272db4f72088c3631d2f6184eca4f7e872ac5535 管道阻塞问题
