### ISSUE TITLE
Graph 是如何部署的？

### ISSUE THREAD

**Issue by zzl0** [XiaoMi/open-falcon#3]
请问 Graph 数据的有副本（写多份）吗？我在 transfer 和 graph 里面没有找到相关的参数

**Comment by laiwei** [comment]
目前没有双写

不过你可以使用migrating配置项间接达到双写的目的

或者自行备份磁盘数据

**Comment by zzl0** [comment]
嗯，多谢lai总。不过用 migrating 来 hack 的话，在真正因为加减节点而需要 migrating 时，就会比较乱。而如果备份恢复的话会丢一段时间的数据。

另外，一个小问题，open-falcon 在 migrating 数据时，历史数据会做迁移吗？看文档好像是不管历史数据了
