### ISSUE TITLE
报警策略不生效

### ISSUE THREAD

**Issue by worldlove** [XiaoMi/open-falcon#31]
依据该网页逐项检查http://book.open-falcon.com/zh/faq/alarm.html，
curl 127.0.0.1:6081/history/XXX可以获取到数据，发送邮件和短信的api都是无效的配置，但是9912端口没有“未恢复的报警”，报警没有生效，请问我该怎么排查错误

**Comment by itxx00** [comment]
你的报警策略是什么

**Comment by worldlove** [comment]
cpu.busy 	all(#1)>=10%	10	0
mem.memfree.percent [内存空闲大于10%]	all(#3)>=10%	3000	0

**Comment by worldlove** [comment]
策略应该是没问题吧？我改如何排查问题呢？
