### ISSUE TITLE
部分agent端无法在dashboard中显示问题

### ISSUE THREAD

**Issue by cyn9145** [XiaoMi/open-falcon#32]
我在测试环境搭建了open-falcon服务端，但是在新添加监控节点的时候，发现新添加的节点，在dashboard中能搜索到，但是图表没有数据，然后验证节点IP+端口，发现web界面是有数据的，而且./falcon-agent --check发现都是OK，然后查看节点日志，没有错误日志，服务端的transfer日志，已经监听的端口

**Comment by zhansheng** [comment]
这个有解吗？我遇到了类似的问题

**Comment by laiwei** [comment]
请排查一下“绘图”这条链路 在book.open-falcon.org 有描述

**Comment by oldbelvey** [comment]
我的也是同样的问题，按照book.open-falcon.org说明的进行检查了一遍没有问题。但web中的dashboard中就是没有内容。此时我再次回到新安装的agent时检查此机器上的时间，发现问题了，时间不一致，同步时间后，问题搞定。

**Comment by vainly** [comment]
自定义的push数据 key_0.cpu.percent key_1.cpu.percent  类似这样的 metric 上传，在dashboard面板上查不出数据，不知为何。

**Comment by laiwei** [comment]
@vainly 需要周期性的上报数据

**Comment by keiler2018** [comment]
我自定义数据 endpoint 已经有了，counters也能搜索到，但是 具体的值 就是没有。
数据 也没看出问题
[{\"metric\": \"cpu\", \"endpoint\": \"pc001\", \"timestamp\":1603823887, \"step\":60,\"value\":12.2,\"counterType\":\"GAUGE\",\"tags\": \"cpu=use\"},{\"metric\": \"cpu\", \"endpoint\": \"pc002\", \"timestamp\":1603823887, \"step\":60,\"value\":22.4,\"counterType\":\"GAUGE\",\"tags\": \"cpu=use\"},{\"metric\": \"cpu\", \"endpoint\": \"pc003\", \"timestamp\":1603823887, \"step\":60,\"value\":32.8,\"counterType\":\"GAUGE\",\"tags\": \"cpu=use\"}]

**Comment by keiler2018** [comment]
> 我的也是同样的问题，按照book.open-falcon.org说明的进行检查了一遍没有问题。但web中的dashboard中就是没有内容。此时我再次回到新安装的agent时检查此机器上的时间，发现问题了，时间不一致，同步时间后，问题搞定。

你说的是 agent 获取的时间戳 和服务器的时间 不一致么
