### ISSUE TITLE
所有的服务启动成功，但是telnet服务端口不通？

### ISSUE THREAD

**Issue by jshancn** [XiaoMi/open-falcon#33]
我按照官方的步骤进行了安装，在启动transfer和agent等组件的时候，启动过程正常，日志输出也是正常的，用netstat和ps查看端口和进程的情况也是正确的。但是curl服务没有返回ok，然后我telnet了一下监听的端口们，发现都不通？起了其他的服务试了一下同样的端口，发现可以访问，排除防火墙的原因。请问下大家知道这是什么原因吗？

**Comment by hackstoic** [comment]
我们这边部署falcon的时候没有遇到这种情况， 你把ps， netstat， curl， telnet的信息贴出来看看。 另外执行ss -tln看看是否有对应的端口侦听，还可以用tcpdump抓包看看，比如tcpdump host xxx and port 1988 看看。 希望对你有帮助。

**Comment by jshancn** [comment]
![begin](https://cloud.githubusercontent.com/assets/9959970/15531610/d339c644-228d-11e6-96e1-e5286e3774ad.png)
开始启动和启动日志。
![curl](https://cloud.githubusercontent.com/assets/9959970/15531643/fde370de-228d-11e6-97e0-0c56de238994.png)
curl发送请求。
![telnet](https://cloud.githubusercontent.com/assets/9959970/15531679/3472942c-228e-11e6-815c-0f4565478c39.png)
telnet 6060。
![netstat](https://cloud.githubusercontent.com/assets/9959970/15531723/6b368b26-228e-11e6-87ab-c37ebd37c617.png)
netstat
![ss](https://cloud.githubusercontent.com/assets/9959970/15531738/7e114cfe-228e-11e6-9f93-3350625324bb.png)
ss
![ps](https://cloud.githubusercontent.com/assets/9959970/15531748/8fdeec48-228e-11e6-9c26-4cf0e4e752d6.png)
ps
这些好像都没什么异常，因为不是root账户，所以没法使用tcpdump，请大神帮忙看看。。。还有这个运行账户的主目录不是普通的/home/$USER,不知道与这个有没有关系。

**Comment by jshancn** [comment]
已经解决了，把配置中的所有127.0.0.1和0.0.0.0改成内网ip就能telnet通了。
