### ISSUE TITLE
关于二次开发文档能写的详细点吗？

### ISSUE THREAD

**Issue by tanxiaolong** [XiaoMi/open-falcon#35]
想自定义一些api接口，但是在api.py里写了一个测试route，访问后404，然后问了一下群里的管理员，说是需要二次开发，文档关于二次开发的内容太少了，希望能增加以便满足更多的自定义需求。谢谢xiaomi

**Comment by laiwei** [comment]
二次开发这块，文档还需要补充，到年底，会有完善
