### ISSUE TITLE
业务监控的问题

### ISSUE THREAD

**Issue by seanzhau** [XiaoMi/open-falcon#37]
请问open-falcon有没有业务方面的监控，比如对业务逻辑、业务流程的监控

**Comment by itxx00** [comment]
falcon提供了push监控数据的api，只需要根据自己的业务需求把监控指标push到falcon的agent就可以了

**Comment by laiwei** [comment]
@seanzhau 

接下来，我们会放出针对不同语言的SDK，来更好的完善业务监控

**Comment by weijie199148** [comment]
请问如果 只是监控单个服务的运转状态，只使用falcon的报警处理功能，应该调用哪个接口可以实现
