### ISSUE TITLE
关于分布式graph部署遇到的问题

### ISSUE THREAD

**Issue by tanxiaolong** [XiaoMi/open-falcon#39]
在部署多个graph的时候（我用AB来区别吧），在文档的说明下部署成功。
但是在B的log里面会不定时（也可能是定时）的输出“errno: 0x023a, str:opening error”，每次输出n多行。

我刚开始以为没有部署成功，当我把A停掉之后，图像有些许影响，不过依然有图像，说明部署是成功的。
然后我grep源码想查看是哪里有写“errno: 0x023a, str:opening error”，但并未找到。

请问@laiwei @itxx00 有遇到此类问题吗？

**Comment by hitripod** [comment]
https://github.com/open-falcon/graph/issues/17

**Comment by yubo** [comment]
这是一个警告信息，对使用没有影响，错误码在 https://github.com/yubo/rrdlite/blob/master/rrd_error.h 处定义
