### ISSUE TITLE
关于监控进程的问题

### ISSUE THREAD

**Issue by wekay102200** [XiaoMi/open-falcon#43]
请问open-falcon监控进程除了进程停掉之后能报警之外，还能不能自动重启进程？这个zabbbix是可以做到的。

**Comment by 710leo** [comment]
@wekay102200  falcon-agent只是负责监控进程的状态，没有重启进程的功能
不过当进程停掉发出报警后，可以触发一个callback，你可以写一个程序，功能如下：当接收到callback后，把停掉的服务起起来
