### ISSUE TITLE
agent模块plugin机制插件变更需重启agent才生效

### ISSUE THREAD

**Issue by yindashan** [XiaoMi/open-falcon#6]
HBS代码现在是对host绑定的插件目录计算md5值，只有在插件目录发生变更的情况下，才会返回正确的值，否则返回空数组，代码如下：
plugins := cache.GetPlugins(args.Hostname)
	checksum := ""
	if len(plugins) > 0 {
		checksum = utils.Md5(strings.Join(plugins, ""))
	}

	if args.Checksum == checksum {
		reply.Plugins = []string{}
	} else {
		reply.Plugins = plugins
	}
Agent代码中也会根据checksum进行相应的判断，如果checksum没有发生变更，直接跳过了本次循环，进入下一次循环，这样就不会遍历插件目录下面新增的插件了，代码如下：
if resp.Checksum == checksum {
			goto REST
		}
解决方案，可以玩一个trick，实现不需要重启自动生效。在hbs代码中直接返回插件目录，不管是否发生变更(每次都是从hbs的内存中取，效率不是问题)。在agent中注释掉下面代码：
if resp.Checksum == checksum {
			goto REST
		}

**Comment by laiwei** [comment]
:+1: 
这个现象收到多次反馈了

@yindashan 能否发一个pull-request来解决掉这个问题

**Comment by UlricQin** [comment]
已修复该bug

**Comment by laiwei** [comment]
:+1: 鼓掌
