### ISSUE TITLE
nodata添加后不起作用？

### ISSUE THREAD

**Issue by Sexisnull** [XiaoMi/open-falcon#64]
请求帮助！
在按照帮助文档部署后，在nodata添加监控时发现不起作用，监控默认的agent.alive，采用默认模板。
nodata log日志如下
2018/11/15 14:43:20 collector_cron.go:82: fetchItemAndStore fail, size:0, error:json: cannot unmarshal object into Go value of type []*model.GraphLastResp
2018/11/15 14:43:20 collector_cron.go:85: fetchItemAndStore keys:[test/agent.alive], key_size:1, ret_size:0
2018/11/15 14:43:20 collector_cron.go:31: collect cron, cnt 0, time 0s, start 2018-11-15 14:43:20
2018/11/15 14:43:40 collector_cron.go:82: fetchItemAndStore fail, size:0, error:json: cannot unmarshal object into Go value of type []*model.GraphLastResp
2018/11/15 14:43:40 collector_cron.go:85: fetchItemAndStore keys:[test/agent.alive], key_size:1, ret_size:0

任何帮助都不胜感激！谢谢！

**Comment by mykioer** [comment]
发配置截图
