### ISSUE TITLE
补充资料中关于进程资源监控指标的配置内容

### ISSUE THREAD

**Issue by zhaoxiaole** [XiaoMi/open-falcon#9]

**Comment by laiwei** [comment]
这是补充文档吗？

可以直接提交一个pull request哈

**Comment by zhaoxiaole** [comment]
麻烦您在资料中补充一下进程资源监控指标的配置内容



zhaoxiaole1993@sina.com
 
发件人： laiwei
发送时间： 2015-09-22 11:27
收件人： XiaoMi/open-falcon
抄送： zhaoxiaole
主题： Re: [open-falcon] 补充资料中关于进程资源监控指标的配置内容 (#9)
这是补充文档吗？
可以直接提交一个pull request哈
